package_linter.py
Salut,
Un peu de nettoyage du code pour le rendre plus pythonic. À part le fix (j'ai fait ce qui me semblait évident) le comportement n'est pas modifié.
=> Fix+pythonic style

package_linter.py
=> [enh] script returns 1 if there are errors fix #12

package_linter.py
Remove every comments from file content to avoid false positives.
=> [fix] don't take comments into account

package_linter.py
- '$1' arg retrieval is now deprecated.
=> [enh] #18: check arguments retrieval is done with env var.

package_linter.py
Could be merge once YunoHost 2.6 will be released as stable.
=> [mod] #5: remove 'sudo' cmd prefix check for YnH 2.6.

package_linter.py
Some test were not accurate (exit and set -eu)
A lot of YEP are not tested.
This PR implements a warning level and a wrong but no sure level.
It had some new test, some of them are not so linked to the role of a linter but it test some YEP, feel free to move it in an other place.
Remove all print that say "ok", just display the failing test
just run package linter on some apps
Opinion needed
Might need a refactoring
=> [enh] Add warning and some test

package_linter.py
(Credits goes to fr0g for spotting this ;))
(This is a blind/untested commit though)
=> Fix license test + improve message

package_linter.py
Moar refactor stuff ... in particular motivated to ease the integration of https://github.com/YunoHost/package_linter/pull/57 which is yet-another-example where we want to do consistency cross-checks between scripts / manifest ... and we should avoid to re-read scripts everytime.
=> Refactor some stuff into an app class

package_linter.py
To add a check for the present of the source of _common.sh file. Check if duplicate, absent or not correct (execution context).
Ref https://github.com/YunoHost/package_linter/issues/50
=> Add test of common file

package_linter.py
This fix cases mentionned in https://github.com/YunoHost/package_linter/issues/53
=> Check for duplicated key in json + empty description

package_linter.py
c.f. https://github.com/YunoHost/package_linter/issues/48
=> Add a warning if required YunoHost version is still 2.x

package_linter.py
c.f. https://github.com/YunoHost/package_linter/issues/59
This is a bit quick-and-dirty implementation but I doubt we'll be able to make anything cleaner without a proper nginx-like file parsing utility.
=> Check for path traversal issue

package_linter.py
c.f. https://github.com/YunoHost/package_linter/issues/52 and YEP 3.7
=> Check and report usage of custom apt sources

package_linter.py
=> fix sudo detection

package_linter.py
- fix link to ynh_add_extra_apt_repos
- add an exception to solve https://github.com/YunoHost/package_linter/issues/71
=> fix ynh_add_extra_apt_repos

lib/nginxparser/nginxparser.py, package_linter.py
| App | Level | Results | Nginx path traversal |
| :----: | :----: | :----: | :----: |
| wordpress | 8 | :green_heart: | |
| wallabag2 | 8 | :green_heart: | |
| synapse | 8 | :green_heart: | |
| strut | 8 | :green_heart: | |
| piwigo | 8 | 1 :warning: | |
| opensondage | 8 | :green_heart: | |
| leed | 8 | 2 :warning: | |
| gitlab | 8 | 1 :warning: | |
| etherpad_mypads | 8 | 2 :warning: | |
| dokuwiki | 8 | :green_heart: | |
| z-push | 7 | :green_heart: | :red_circle: (out of CI's scope, TBC) |
| zerobin | 7 | :green_heart: | |
| zap | 7 | 8 :warning: | :red_circle:  (maybe false negative, TBC)  |
| zabbix | 7 | 6 :warning: | |
| writefreely | 7 | 1 :warning: | |
| wikijs | 7 | :green_heart: | |
| wemawema | 7 | 10 :warning: | :red_circle: (confirmed on CI) |
| wekan | 7 | 1 :warning: | | …
=> Misc improvements

package_linter.py
Now that 4.1 is there ...
I'm trying to think about some way to automate the required changes considering stuff has to be done for the 150+ apps but it ain't trivial ...
=> Report legacy permission stuff (as info)

package_linter.py
Opinionated and sometimes ridiculous fixes on wordings and typos. Feel free to tell me to GTFO. 😇
=> Fix typos, rewordings

package_linter.py
[Issue](https://github.com/YunoHost/issues/issues/2122)
=> Warn when using ynh_script_progression in _common.sh

package_linter.py
=> Fix jsonschema dependency installation

lib/nginxparser/nginxparser.py, package_linter.py, tox.ini
No real issue, fixed Flake8 complaints, some around RegEx pattern actually useful (?)
=> Fixed (most) linter complaints.

package_linter.py
Show lines that are not 'proper' `more_set_headers` calls for ease of fixing.
=> Show offending lines for 'more_set_headers'

package_linter.py
=> nginx check regex in location field

package_linter.py
Reverts YunoHost/package_linter#124
The CI is buggy right now
=> Revert "nginx check regex in location field"

package_linter.py
* Reapply original code fro @kay0u 
* Fix the path to the nginx file
=> Fix nginx regex

package_linter.py
Revert #132 
The original issue has been fixed by #134
=> Change misc_nginx_check_regex_in_location from Info to Warning

package_linter.py
OK for jellyfin_ynh, for instance
=> Lower needed exposed ports warning to info

package_linter.py
Based on https://github.com/YunoHost/apps/pull/2402
=> Lint the tests.toml and config_panel.toml with schemas too

package_linter.py
- *Description of why you made this PR, what is its purpose*
- *And how do you relevantly fix that problem*
=> Fix package linter

.gitignore, lib/lib_package_linter.py, lib/print.py, package_linter.py, requirements.txt, tests/test_app.py, tests/test_catalog.py, tests/test_configurations.py, tests/test_manifest.py, tests/test_scripts.py
- `package_linter.py package_ynh --json` produces no output
- Fix sharing of `global` between modules.
=> Fixed json output

tests/test_app.py, tests/test_catalog.py, tests/test_configurations.py, tests/test_manifest.py
It was introduced in python3.11, available on bookworm
- *Description of why you made this PR, what is its purpose*
- *And how do you relevantly fix that problem*
=> Use the new standard tomllib library

lib/lib_package_linter.py, lib/nginxparser/nginxparser.py, lib/print.py, package_linter.py, tests/test_app.py, tests/test_catalog.py, tests/test_configurations.py, tests/test_manifest.py, tests/test_scripts.py
- *Description of why you made this PR, what is its purpose*
- *And how do you relevantly fix that problem*
=> Python Typing

lib/lib_package_linter.py, package_linter.py, tests/test_app.py, tests/test_catalog.py, tests/test_configurations.py, tests/test_manifest.py, tests/test_scripts.py
- *Description of why you made this PR, what is its purpose*
- *And how do you relevantly fix that problem*
=> Use pathlib.Path
