YunoHost/package_linter

package_linter.py
Currently, any occurence of the "exit" string is considered as a use of the exit
shell function. While my solution is still clumsy (we should be using a bash
parser), I think it's a bit less clumsy, it triggers less false positives :)
=> [fix] search for "exit" more accurately

package_linter.py
it looks clever when you only use package_linter as standalone, but once you run it inside package_check, you loose previous output, which is not dramatic but annoying. A tool should not decide of you clear or not your console. Let's fix this.
=> remove `clear`

package_linter.py
This follows https://github.com/YunoHost/package_linter/pull/38
Many packages have basic issues to be solved, that may create side effects for end-user.
Here us a new warning to make sure dependencies are updated on upgrade and present on restore.
=> Add dependencies consistency check

package_linter.py
Meh, I was just implementing new features and just noticed too many weird or buggy things so I'm ending up with this :|.
- I refactored and clean various parts to improve structure and readability
- There were many tests not behaving properly due to the use of shlex ... some of them I still don't understand. Fixed it by checking a raw reading. Maybe that brings false-negative, but at least there should be way less false-positive. We can improve later with regex and stuff like this, or get a better understanding of shlex.
- Added check for use of deprecated practices : 
- `yunohost app setting`
- `yunohost app checkurl`
- `yunohost app checkport`
- `yunohost app initdb`
- `exit`
- separate `php-fpm.ini`
- `dd if=/dev/urandom` or `openssl rand` for random string generation
- And other check …
=> Refactor / clean, and report deprecated practices

package_linter.py
The current checks for arguments type (in manifest.json) are a bit weird...
I reworked this part such that it reports : 
- missing argument type (as an error)
- unrecognized argument type (as a warning)
- use of 'choices' only to choose between 'Yes' and 'No' (or True and False). Instead, a boolean arg should be used (better for i18n ?)
This fixes https://github.com/YunoHost/package_linter/issues/2
=> Report missing or bad manifest arg type, or unecessary 'choices' usage

package_linter.py
c.f. https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx and https://github.com/YunoHost-Apps/nextcloud_ynh/pull/160
Apps should not use `add_header` in nginx conf, but rather `more_set_headers` ... 
This adds a warning in package_linter.
=> Warn about the use of add_header in nginx conf

package_linter.py
c.f. https://github.com/YunoHost/example_ynh/pull/58 and https://github.com/YunoHost/yunohost/pull/634
This adds a check in package check because you can easily forget to use those. Yet it's quite frustating for the user to launch an app install and just see the pacman hang forever with no feedback (except possibly warnings)
=> Recommend ynh_print_info or ynh_script_progression usage in the install script

package_linter.py
Sooo, again some refactoring / reworking ... because shlex was still doing some weird stuff as reported by @kay0u (see what you make me do ! :stuck_out_tongue_closed_eyes: ) and all those check with `script["shlex"]` and `script["raw"]` were weird...
So I went for feeding line one-by-one to shlex, and implementing a `contains` method for the new `Script` class ... Now it should be technically cleaner ... though I discovered that parsing lines one-by-one are not 100% a good idea if you have multiple-line string. So for instance, running on lstu will display : 
```
[Upgrade Script]
! Could not parse this line (No closing quotation) : echo "The new version of LSTU provide an admin and a stats area which required a password. 
! Could not parse this line (No closing quotation) : This password …
```
=> Rework script parsing : line-per-line (still using shlex)

package_linter.py
Because my zabbix app install correctly snmpd and I have a YEP2.1 at any linter check.
So if a new service is detected in manifest, check if the installation is present in the install file.
=> add check service in install file match with manifest (new services)

package_linter.py
c.f. https://github.com/YunoHost/package_linter/issues/51
is_public means something different across the various apps and users are regularly confused about this
=> Encourage packagers to detail what is_public means

package_linter.py
Alright folks, I really fed up about still seeing damn yunohost instance being destroyed with crazy issues related to apps who installed php 7.x via a custom repo ... Latest example being https://forum.yunohost.org/t/erreur-dinstallation-wallabag-probleme-avec-php7-0-tidy/7724
Most probably caused by Monica, but could have been any app.
So this PR improves the detection of apps messing with `/etc/apt/sources.list*`  and **reports it as an error**, effectively downgrading them to level 4 (or 3 ?) though if it was me I would even just downgrade them to level 0 and tell the maintainer to just use the new helpers ...
=> Improve sources list detection + report messing with sources.list as an error (if not using the helpers)

package_linter.py
Not sur if it's a good idea, but just sad to see https://github.com/labriqueinternet/vpnclient_ynh at[ level 5 instead of 7](https://ci-apps.yunohost.org/ci/job/3479) because it's not in YunoHost-App
=> adding labriqueinternet as autorized repository

package_linter.py
since YunoHost 3.6 release (https://forum.yunohost.org/t/yunohost-3-6-release-sortie-de-yunohost-3-6/8359),
apps.json is the standard repo for packaging Apps, making YEP1.2 obsolete.
The code has been changed but other documentation and misc must be updated as well,
consider this PR as collaborative.
=> Adding apps.json new repository paradigm on linter

package_linter.py
Allow the use of 0 (zéro) in ID field in manifest for app like **20euros**, **cubiks2048**
=> Allow 0 to be used in ID field

package_linter.py
when using postgres service, install and restore script must call test_if_first_run. But then, the ynh service is already installed.
So instead of checking for yunohost service add, we check for ynh_psql_test_if_first_run.
=> Enforce ynh_postgres_test_if_first_run and not yunohost service add

package_linter.py
Sooooo started working on this mostly because I wanted to be able to do bulk analysis of the linter results on all apps (or all level 5+ apps) to then be able to flag some stuff as errors (instead of warnings) and be able to check what apps are impacted.
For this, I needed a json output with some error-code-like flags, and ended up refactoring the entire script to have more of a atomic/unit-test-like approach (though could still be improved...) instead of huge functions calling `print()`
After this, I ran a study over all the level 5+ apps to check what could / should now be reported as error ... and also what's the status of some tests like path traversal issue over all apps ...
So far this refactoring introduces the following "regressions" on currently level 5+ apps (meaning releasing …
=> Refactor with a more "unit-test" like approach, + enforce some tests as error (instead of warning) for moaaar quality

package_linter.py
Sooooo this is yet another me-being-obsessed-with-quality-metrics-and-tools™, and kind of a follow up of last meeting where I was mentioning the idea of redefining level 7 and 8.
This PR proposes to add two new "meta" tests.
First one is the "long-term good-quality score", which is computed by analyzing the history of apps.json over the last 12 months and checking how many periods the app was known + flagged working + level >= 5. If that's the case for 90% of the periods, the app is considered as "long-term good quality" (all the parameters are debatable of course - maybe one year is too much ...)
(N.B. : this got updated compared to original post)
A new definition for level 7 and 8 is proposed : 
- "New" Level 7 = (previous level 7 requirements) + No error / warnings reported by the …
=> New definitions for level 7, 8 (and 9)

package_linter.py
Trying to resolve the case where in `manifest.json`, version revision number is > than 9: cf leed_ynh version is `1.8.3~ynh10`:  https://ci-apps.yunohost.org/ci/job/854
=> Fix error when revision version > 9

package_linter.py
It's now been a while since the release of 4.1 and thanks to the hard work of the packaging team we're down to only a handful of level 7+ apps still reporting this : 
jirafeau
leed
libreto
lstu
lufi
lutim
mailman
privatebin
ttrss
Proposing to switch this to a warning to further encourage getting rid of this legacy ... What got me triggered is somebody encountering the infamous issue on jirafeau with "my domain got a dash which got transformed into a dot and the url permission is found to be invalid, hence install crash" (that's because of the old perm regex format) (though migrating old `protected_regex` is not trivial..)
=> `set_legacy_permission` to report a warning instead of info

package_linter.py
- Fix https://github.com/YunoHost/issues/issues/1964
=> Use an Info instead of a Warning for packages that are not in the YunoHost-Apps organisation

package_linter.py
as php-pear, php-php-gettext is not available as phpx.y-php-gettext
=> php-php-gettext exception

package_linter.py
- Fix a bug in package_linter if `upstream.website` is not defined in the `manifest.json`.
=> fix: default value for manifest.upstream.website

package_linter.py
Allow packages to be a list. Also, use the same splitting logic as in yunohost source code.
=> Fix package linter on apt list

package_linter.py
Make "x y" proper list of dependencies [`x`, `y`]  rather that of [`x y`]
=> Consistently parse apt dependencies.

package_linter.py
While stupid `more_set_headers                              "Header: Value"` is a valid syntax.
=> Allow multiple whitespace after 'more_set_headers'

package_linter.py
Current regex will match any of the ten line after the official helper files starting with the string `source`. 
Thus, in my specific case in an install script for which I declare a variable named `source_filename=$(basename $upstream_source_url)`, the linter will unecessarily display the following warning: `    ! Please avoid sourcing additional helpers after the official helpers (in this case file _filename=$(basename$upstream__url)) `.
As it should be only interested in matching the command `source` (`source path/to/file`), a space should be appended to the current regex.
=> Fix regex in helpers_sourcing_after_official()

package_linter.py
check if a package config file uses `0.0.0.0` or `::` to bind IPs
if so, there is a risk of bind a public IP
this can result in a security issue as the SSO can be bypassed by knowing a public IP (typically an IPv6) and the app port.
=> add bind_public_ip check

package_linter.py
as talked with @Tagadda, the fact that it's a warning isn't very appropriate
=> Downgrade misc_nginx_check_regex_in_location from Warning to Info

package_linter.py
grep will return 0 when it finds matches.
In our case, when it finds matches, we need to print the warning.
=> Fix nginx test

.github/autoblack.yml
This add the autoblack action from moulinette on this repository (while adapting the branch name).
This action automatically generate a pull request to format the code with black so we don't lose time by having to run it manually when needed.
=> ci: add autoblacks actions

package_linter.py
since #141, `bind_public_ip` returns unnecessarily long (and confusing) path:
`/tmp/package_check.O22Mlb/app_folder/conf/server.toml:5`
fix this by showing the path from the app folder:
```
conf/blah:1
conf/test/bleh:1
```
=> Fix showed path in 'bind_public_ip' message

package_linter.py
> - settings.js:154: Binding to '0.0.0.0' or '::' can result in a security issue as the reverse proxy and the SSO can be bypassed by knowing a public IP (typically an IPv6) and the app port. lease be sure that this behavior is intentional. Maybe use '127.0.0.1' or '::1' instead.
https://ci-apps-dev.yunohost.org/ci/job/13846
The reported code is in fact a comment:
```
/** By default, the Node-RED UI accepts connections on all IPv4 interfaces.
* To listen on all IPv6 addresses, set uiHost to "::",
* The following property can be used to listen on a specific interface. For
* example, the following would only allow connections from the local machine.
*/
```
https://github.com/YunoHost-Apps/nodered_ynh/blob/master/conf/settings.js#L153C1-L157C8
add javascript comment syntax (`/**` & `*`) to …
=> bind_public_ip: fix for .js config files

package_linter.py
> ! (Requires Yunohost 4.3) When using ynh_exec_*, please don't wrap your command between quotes (typically DONT write ynh_exec_warn_less 'foo --bar --baz')
yeah but i don't:
`ynh_exec_warn_less "$install_dir/script/convos" install`
so adjusting the regex to check if the line also finishes with a quoting mark
=> Fix bad_ynh_exec_syntax

package_linter.py
False positive on https://github.com/YunoHost-Apps/synapse_ynh/blob/6ed1dd9a9f73bce6c55040a5ae267c266577b201/doc/ADMIN.md#add-permanent-rule-on-ssowat
Exclude `/etc/ssowat/conf.json.persistent` in `/doc` it's not black magick when it's documented
=> Avoid ssowat config persistent error on /doc

package_linter.py
- `sed -i` is often used instead of `ynh_replace_string`, not `ynh_add_config`
- added mention of `ynh_replace_string` before `ynh_add_config`
=> 'sed -i' info: added mention of 'ynh_replace_string'

package_linter.py
- the level 8 disqualification message is not explicit on its stakes
- edit it to make explicit why the package is disqualified for level 8
=> makes level 8 disqualification explicit

package_linter.py
Do not delete logs on app removal, else they will be erased if the app upgrade fails. This is handled by the core.
=> Do not delete logs on app removal

tests/test_configurations.py
In the whole catalog, we never saw 'Can't open/read ...' on real text files, so we can assume it's safe.
Closes #166
=> When checking conf files, we need to ignore files that do not look like text files

tests/test_issues.py
- https://ci-apps-dev.yunohost.org/ci/job/12415
```
Traceback (most recent call last):
File "/var/www/yunorunner/package_check/./package_linter/package_linter.py", line 40, in <module>
main()
File "/var/www/yunorunner/package_check/./package_linter/package_linter.py", line 35, in main
app = App(args.app_path)
^^^^^^^^^^^^^^^^^^
File "/var/www/yunorunner/package_check/package_linter/tests/test_app.py", line 253, in __init__
self.issues = Issues(self.manifest["id"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/var/www/yunorunner/package_check/package_linter/tests/test_issues.py", line 27, in __init__
repo_url = self.app_list[app]["url"]
~~~~~~~~~~~~~^^^^^
KeyError: 'tuwunel'
```
- `get(whatever, sane_default)`
=> Don't fail on packages from outside of the catalog
